# Antivirus running on MZ. 
#

- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
    install_name: 'utilities-service'
    helm_chart: '{{charts_root}}/utilities'
    is_template: true  
    helm_namespace: default
    helm_values: '{{charts_root}}/utilities/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}

