apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.contactus.serviceName }}
  namespace: {{ .Values.namespace }} 
spec:
  ports:
  - port: {{ .Values.services.contactus.servicePort }}
    targetPort: {{ .Values.services.contactus.containerPort }}
  selector:
    app: {{ .Values.services.contactus.serviceName }}

