apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.prid.serviceName }} 
  namespace: {{ .Values.namespace }} 
spec:
  ports:
  - port: {{ .Values.services.prid.servicePort }}
    targetPort: {{ .Values.services.prid.containerPort }}
  selector:
    app: {{ .Values.services.prid.serviceName }} 

