apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.biosvc.serviceName }} 
  namespace: {{ .Values.namespace }} 
spec:
  ports:
  - port: {{ .Values.services.biosvc.ports.servicePort }}
    targetPort: {{ .Values.services.biosvc.ports.containerPort }}
  selector:
    app: {{ .Values.services.biosvc.serviceName }} 
