---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.name }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.dockerImage }}:{{ .Values.dockerTag }}
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1024m"
          limits:
            memory: "4096Mi"
            cpu: "2048Mi"
        env:
        - name: KEYCLOAK_USER 
          value: {{ .Values.keycloakUser }}
        - name: KEYCLOAK_PASSWORD 
          value: {{ .Values.keycloakPassword }}
        - name: DB_VENDOR 
          value: postgres
        - name: DB_ADDR
          value: {{ .Values.db.host }} 
        - name: DB_PORT
          value: "{{ .Values.db.port }}" 
        - name: DB_USER 
          value: {{ .Values.db.user }} 
        - name: DB_PASSWORD
          value: {{ .Values.db.password }} 
        - name: KEYCLOAK_FRONTEND_URL
          value: {{ .Values.keycloakExternalUrl }}
        - name: JAVA_OPTS
          value: -server {{.Values.keycloakXms}} {{.Values.keycloakXmx}} -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
        ports:
        - containerPort: {{ .Values.containerPort }} 
        readinessProbe:
          tcpSocket:
            port: {{ .Values.containerPort }}  # All defaults used

